- name: Configure named.conf
  template:
    src: named.conf.j2
    dest: /etc/named.conf
    owner: root
    group: named
    mode: '0644'

- name: Create forward zone file
  template:
    src: db.forward.j2
    dest: /var/named/forward.fedora.local
    owner: root
    group: named
    mode: '0644'

- name: Create reverse zone file
  template:
    src: db.reverse.j2
    dest: /var/named/reverse.fedora.local
    owner: root
    group: named
    mode: '0644'